### ISSUE TITLE
Export PPT

### ISSUE THREAD

**Issue by NWCHHRP** [consbio/seedlot-selection-tool#17]
![image](https://user-images.githubusercontent.com/84032755/117846696-87210b80-b236-11eb-926e-96b82574a8e6.png)

No image shows to 'move' the map when exporting to a PPT.

holly NWCH

**Comment by nikmolnar** [comment]
@NWCHHRP Thanks for reporting this issue! I will get it fixed.

**Comment by nikmolnar** [comment]
@NWCHHRP Sorry for not following up on this at the time, but this issue was fixed a while back.
