### ISSUE TITLE
Seedlot Selection Tool bug

### ISSUE THREAD

**Issue by JehanCedric** [consbio/seedlot-selection-tool#23]
Failed multiple times to run job which had run successfully in the past
{
  "action": "runJob",
  "response": {
    "uuid": "1eb10e66-e375-4afe-a782-0ad1a325a418",
    "job": "generate_scores",
    "created": "2021-09-14T14:58:11.240171-07:00",
    "status": "failure",
    "outputs": "{}"
  }
}

**Comment by nikmolnar** [comment]
@JehanCedric thanks for reporting this. There is a problem with the server; I am actively investigating it and will have it fixed as soon as possible.

**Comment by JehanCedric** [comment]
Thanks! I have never had a problem before.

From: Nik Molnar ***@***.***>
Date: Tuesday, September 14, 2021 at 3:06 PM
To: consbio/seedlot-selection-tool ***@***.***>
Cc: Jayawickrama, Keith J.S. ***@***.***>, Mention ***@***.***>
Subject: Re: [consbio/seedlot-selection-tool] Seedlot Selection Tool bug (#23)

[This email originated from outside of OSU. Use caution with links and attachments.]

@JehanCedric<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJehanCedric&data=04%7C01%7Ckeith.jayawickrama%40oregonstate.edu%7C645696c34dc24b18354208d977cbf606%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637672540155658815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AuY3LtdOHDXYLqfTu329KFENtIaI3Ax0vOTCkfo0J18%3D&reserved=0> thanks for reporting this. There is a problem with the server; I am actively investigating it and will have it fixed as soon as possible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconsbio%2Fseedlot-selection-tool%2Fissues%2F23%23issuecomment-919546411&data=04%7C01%7Ckeith.jayawickrama%40oregonstate.edu%7C645696c34dc24b18354208d977cbf606%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637672540155658815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TPH3dx80etEhzPm1vCHX1QDVTdAsahuqOKLojvebhvQ%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVUGY4G4DIVZ42ENHRUK4Y3UB7BPZANCNFSM5EBCRTGQ&data=04%7C01%7Ckeith.jayawickrama%40oregonstate.edu%7C645696c34dc24b18354208d977cbf606%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637672540155668813%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mNY059pT%2FFsIokhVrhoFiwvurAA8bwnx9XKgZn0RKHQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckeith.jayawickrama%40oregonstate.edu%7C645696c34dc24b18354208d977cbf606%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637672540155668813%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K1o0fm4JXmYy3Ag3gL4FiyemK7L2gIxC1LrH8bVto%2BQ%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckeith.jayawickrama%40oregonstate.edu%7C645696c34dc24b18354208d977cbf606%7Cce6d05e13c5e4d6287a84c4a2713c113%7C0%7C0%7C637672540155678806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Xa5dN0CLRL0%2FoD1RxI9bH9U%2BeBx2NCQ7xg8z9ibUQ78%3D&reserved=0>.

**Comment by nikmolnar** [comment]
@JehanCedric: this issue should be fixed now. Please let me know if you have any additional problems!
